/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'surface-dim': '#0b1326',
        'inverse-surface': '#dae2fd',
        'surface-container-low': '#131b2e',
        'outline': '#8c909f',
        'tertiary-container': '#df7412',
        'on-error-container': '#ffdad6',
        'surface-container': '#171f33',
        'surface-tint': '#adc6ff',
        'surface-variant': '#2d3449',
        'tertiary-fixed-dim': '#ffb786',
        'surface-container-lowest': '#060e20',
        'on-error': '#690005',
        'on-primary': '#002e6a',
        'tertiary-fixed': '#ffdcc6',
        'surface-container-high': '#222a3d',
        'secondary-fixed': '#d3e4fe',
        'error-container': '#93000a',
        'inverse-primary': '#005ac2',
        'error': '#ffb4ab',
        'inverse-on-surface': '#283044',
        'surface-bright': '#31394d',
        'primary-container': '#4d8eff',
        'on-secondary': '#213145',
        'primary-fixed': '#d8e2ff',
        'on-primary-container': '#00285d',
        'on-primary-fixed': '#001a42',
        'on-secondary-container': '#a9bad3',
        'secondary': '#b7c8e1',
        'on-background': '#dae2fd',
        'on-tertiary': '#502400',
        'on-primary-fixed-variant': '#004395',
        'on-tertiary-fixed-variant': '#723600',
        'primary': '#adc6ff',
        'tertiary': '#ffb786',
        'on-surface-variant': '#c2c6d6',
        'secondary-container': '#3a4a5f',
        'surface-container-highest': '#2d3449',
        'on-tertiary-container': '#461f00',
        'on-secondary-fixed': '#0b1c30',
        'on-secondary-fixed-variant': '#38485d',
        'on-surface': '#dae2fd',
        'secondary-fixed-dim': '#b7c8e1',
        'primary-fixed-dim': '#adc6ff',
        'outline-variant': '#424754',
        'on-tertiary-fixed': '#311400',
        'surface': '#0b1326',
        'background': '#0b1326',
        // SOC compatibility tokens
        soc: {
          base: '#0b1326',
          panel: '#131b2e',
          card: '#171f33',
          cardHover: '#222a3d',
          border: '#424754',
          blue: '#4d8eff',
        },
      },
      borderRadius: {
        'DEFAULT': '0.125rem',
        'lg': '0.25rem',
        'xl': '0.5rem',
        'full': '0.75rem',
      },
      spacing: {
        'margin-desktop': '32px',
        'container-max-width': '1600px',
        'gutter': '16px',
        'unit': '4px',
        'margin-mobile': '16px',
      },
      fontFamily: {
        'body-sm': ['Inter', 'sans-serif'],
        'label-caps': ['JetBrains Mono', 'monospace'],
        'data-mono': ['JetBrains Mono', 'monospace'],
        'title-sm': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'display-lg': ['Inter', 'sans-serif'],
        'sans': ['Inter', 'sans-serif'],
        'mono': ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'body-sm': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'label-caps': ['11px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '700' }],
        'data-mono': ['13px', { lineHeight: '16px', fontWeight: '400' }],
        'title-sm': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'display-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
};
